#pragma once

using namespace ATL;

template <class T>
class CProxy_ISessionObjectEvents : public IConnectionPointImpl<T, &__uuidof(_ISessionObjectEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
