// SessionStore.h : Declaration of SessionStore constants

#pragma once
#ifndef _SESSIONSTORE_H_
#define _SESSIONSTORE_H_


/*ERROR CODES*/

//success
#define SSTORE_S_OK				MAKE_HRESULT(SEVERITY_SUCCESS, FACILITY_ITF, 0x00)
#define SSTORE_S_ITEMNOTFOUND	MAKE_HRESULT(SEVERITY_SUCCESS, FACILITY_ITF, 0x01)

//error
#define SSTORE_E_FAILED			MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x100)
#define SSTORE_E_ITEMLOCKED		MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x101)
#define SSTORE_E_GETFAILED		MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x102)
#define SSTORE_E_SETFAILED		MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x103)

/**/



#endif // !_SESSIONSTORE_H_ 